### PR TITLE
copyZapAddOn: Update the help information.

### PR DESCRIPTION
**Pull request by Hypro999**
Change the copy location from $rootDir/../zaproxy/src/plugin/
to $rootDir/../zaproxy/zap/src/main/dist/plugin/.
@thc202: requesting review.

### CODE REVIEW

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s): 
- https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff
- https://wiki.eclipse.org/EGit/User_Guide/Commit#Signing_off_commits

**Comment by thc202** [comment]
Could you update the changelog?

**Comment by Hypro999** [comment]
Will do.

**Comment by thc202** [comment]
Thanks!

**Comment by Hypro999** [comment]
Thanks for the review!

**Pull request merged**
